#!/usr/bin/perl -w

# Generate usys.S, the stubs for syscalls.

print "# generated by usys.pl - do not edit\n";

print "#include \"kernel/syscall.h\"\n";

# So when you call fork() in user space:
# 1. The C program jumps to this stub.
# 2. Stub puts syscall number into register a7.
# 3. Executes ecall, which traps into the kernel.
# So when ecall happens:
# - CPU traps into kernel.
# - Kernel trap handler calls syscall().
# - syscall() looks up correct function and executes it.

sub entry {
    my $name = shift;
    print ".global $name\n";
    print "${name}:\n";
    print " li a7, SYS_${name}\n";
    print " ecall\n";
    print " ret\n";
}
# add entry for sysinfo
entry("sysinfo");

entry("fork");
entry("exit");
entry("wait");
entry("pipe");
entry("read");
entry("write");
entry("close");
entry("kill");
entry("exec");
entry("open");
entry("mknod");
entry("unlink");
entry("fstat");
entry("link");
entry("mkdir");
entry("chdir");
entry("dup");
entry("getpid");
entry("sbrk");
entry("sleep");
entry("uptime");


